### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by Parth-ops** [ACM-VIT/todo-app#12]
The current version of the Readme file has errors and can be confusing for new contributors.
@ThPadelis I would like to fix this issue.

**Comment by nakshatraraghav** [comment]
@Parth-ops how would you change the readme file? can you specify the changes you wish to make.

**Comment by Parth-ops** [comment]
![image](https://user-images.githubusercontent.com/63533466/195937768-7ed4d3bb-afa4-49eb-a756-5eba5481c75c.png)

These two commands are invalid, I tried them. I found the right ones.

**Comment by nakshatraraghav** [comment]
@Parth-ops sure go ahead!
