### ISSUE TITLE
Implement the search todo functionality

### ISSUE THREAD

**Issue by nakshatraraghav** [ACM-VIT/todo-app#5]
User enters the text of the to-do they want to search in the navbar search box, show suitable results in the **_Your Todos_** section.

**Comment by jsvigneshkanna** [comment]
Assign this to my name please

**Comment by nakshatraraghav** [comment]
Sure, go ahead!

**Comment by ThPadelis** [comment]
If this remains unassigned, I could also help with it

**Comment by nakshatraraghav** [comment]
@ThPadelis sure go ahead, thanks!

**Comment by nakshatraraghav** [comment]
Search functionality has been implemented! by @ThPadelis
